### PR TITLE
Created 200x200 image for Facebook

### PR DESCRIPTION
**Pull request by joshuabremer**

### CODE REVIEW

**Comment by jcbremer** [comment]
Its showing the point website now? WTF

What am I doing wrong?

Jason Bremer
843.670.8996
cardinaldesigns.info

**Comment by joshuabremer** [comment]
@jcbremer Let me look at this. I'm reading about the Facebook Web Crawler right. I kind of feel bad I took you down this annoying road.

**Comment by jcbremer** [comment]
There it is? I’ll look at your code.

Jason Bremer
843.670.8996
cardinaldesigns.info

**Comment by jcbremer** [comment]
I see what you did. For some reason I thought the logo used on Facebook also needed to be in the website somewhere. I was trying to link the logo with the one from the homepage. Didn’t realize I could create a new one for it.

Jason Bremer
843.670.8996
cardinaldesigns.info

**Pull request merged**
